import { describe, expect, it } from "bun:test";
import { createTransferBloomFilter, mayContainTrackedTransfer } from "../src/domain/bloom";
import { keccak256, pad, type Hex } from "viem";
import fixture from "./fixtures/arbitrum-bloom.json";

const unrelated = "0x0000000000000000000000000000000000000001";
const participant = `0x${fixture.logs[0].topics[1].slice(-40)}` as Hex;
const zeroBloom = `0x${"00".repeat(256)}` as Hex;
const fullBloom = `0x${"ff".repeat(256)}` as Hex;

function matches({ logsBloom, addresses }: { logsBloom: string; addresses: Hex[] }): boolean {
  return mayContainTrackedTransfer({
    logsBloom: logsBloom as Hex,
    filter: createTransferBloomFilter({ trackedAddresses: addresses }),
  });
}

describe("Transfer bloom prefilter", () => {
  // Recorded header and log topics from Arbitrum block 507723036, not a bloom
  // generated by our implementation. This guards hashing, padding and bit order.
  it("retains both sender and recipient topics from a real block", () => {
    for (const log of fixture.logs) {
      for (const topic of log.topics.slice(1, 3)) {
        const address = `0x${topic.slice(-40)}` as Hex;
        expect(matches({ logsBloom: fixture.block.logsBloom, addresses: [address] })).toBe(true);
        expect(
          matches({ logsBloom: fixture.block.logsBloom, addresses: [unrelated, address] }),
        ).toBe(true);
      }
    }
  });

  it("does not confuse 20-byte log emitters with padded participant topics", () => {
    expect(
      matches({ logsBloom: fixture.block.logsBloom, addresses: [fixture.logs[0].address as Hex] }),
    ).toBe(false);
  });

  it("skips blocks without tracked participants or without any logs", () => {
    expect(matches({ logsBloom: fixture.block.logsBloom, addresses: [unrelated] })).toBe(false);
    expect(matches({ logsBloom: zeroBloom, addresses: [participant] })).toBe(false);
    expect(matches({ logsBloom: fullBloom, addresses: [] })).toBe(false);
  });

  it("also requires the Transfer signature, not just a participant", () => {
    // Independent byte-oriented construction of a topic-only bloom. It contains
    // the participant but none of the event signature's bits.
    const bloom = new Uint8Array(256);
    const hash = keccak256(pad(participant, { size: 32 }), "bytes");
    for (let i = 0; i < 6; i += 2) {
      const bit = ((hash[i] << 8) | hash[i + 1]) % 2048;
      bloom[255 - Math.floor(bit / 8)] |= 2 ** (bit % 8);
    }
    const logsBloom = `0x${Buffer.from(bloom).toString("hex")}`;
    expect(matches({ logsBloom, addresses: [participant] })).toBe(false);
  });

  it("keeps possible false positives and handles address casing", () => {
    expect(matches({ logsBloom: fullBloom, addresses: [unrelated] })).toBe(true);
    const uppercase = `0x${participant.slice(2).toUpperCase()}` as Hex;
    expect(matches({ logsBloom: fixture.block.logsBloom, addresses: [uppercase] })).toBe(true);
  });

  it("rejects malformed blooms and tracked addresses", () => {
    for (const logsBloom of ["0x", "0x00", `0x${"00".repeat(255)}zz`]) {
      expect(() => matches({ logsBloom, addresses: [participant] })).toThrow();
    }
    expect(() => createTransferBloomFilter({ trackedAddresses: ["0x12"] })).toThrow();
  });
});
